CREATE TABLE `inatelDB`.`TB_UNIVERSITY` (
  `ID_UNIVERSITY` INT NOT NULL,
  `NAME_UNIVERSITY` VARCHAR(45) NOT NULL,
  `COUNTRY_UNIVERSITY` VARCHAR(45) NOT NULL,
  `ALPHA_TWO_CODE_UNIVERSITY` VARCHAR(45) NULL,
  `STATE_PROVINCE_UNIVERSITY` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_UNIVERSITY`));
  
  
CREATE TABLE `inatelDB`.`TB_DOMAIN` (
  `ID_DOMAIN` INT NOT NULL,
  `ID_UNIVERSITY` INT NOT NULL,
  `NAME_DOMAIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_DOMAIN`));


CREATE TABLE `inatelDB`.`TB_WEBPAGE` (
  `ID_WEBPAGE` INT NOT NULL,
  `ID_UNIVERSITY` INT NOT NULL,
  `URL_WEBPAGE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_WEBSITE`));

 
 
ALTER TABLE inatelDB.TB_DOMAIN
ADD CONSTRAINT university_domain_fk 
  FOREIGN KEY (ID_UNIVERSITY)
  REFERENCES TB_UNIVERSITY(id_university);



ALTER TABLE inatelDB.TB_WEBPAGE
ADD CONSTRAINT university_webpage_fk 
  FOREIGN KEY (ID_UNIVERSITY)
  REFERENCES TB_UNIVERSITY(id_university);
 
 
INSERT INTO `inatelDB`.`TB_UNIVERSITY`(`NAME_UNIVERSITY`, `COUNTRY_UNIVERSITY`, `ALPHA_TWO_CODE_UNIVERSITY`)
VALUES ('Instituto Nacional de Telecomunicações - Inatel', 'Brazil', 'BR');


INSERT INTO `inatelDB`.`TB_DOMAIN`(`ID_UNIVERSITY`, `NAME_DOMAIN`)
VALUES (1, 'inatel.br');


INSERT INTO `inatelDB`.`TB_WEBPAGE`(`ID_UNIVERSITY`, `URL_WEBPAGE`)
VALUES (1, 'http://www.inatel.br');

